# Mini Case 1. Demand and Cost

# Introduction

...

$$ 
  y = \alpha + \beta x + \epsilon 
  \label{eq:sample}
$$

```{r result = 'as.is'}
make_quiz("1.01", "At what price would Iceskimo sell 75 cups?",
          paste0("$",c("2.00","2.50","3.00","3.50","4.00")),
          "$2.50", "At a price of $2.50 demand would be \\(100 - 10 \\times 2.50 = 75\\)",
          "In the equation above replace the 0 by 75 and solve for p")

## add 'quiz_' before the quiz number to show the quiz element
uiOutput("quiz_1.01")
```

# Profit function

```{r}
## interactive widget (slider and ggplot)
uiOutput("mc1_profit")
```

# More quiz questions

```{r}
make_quiz("1.02", "If Iceskimo sold 80 units at a price of $10, what must the price sensitivity have been in the Kearny Mesa market?",
          c("-1","-2","-3","-4","-5"),
          "-2",
          "With a price sensitivity of -2, the demand would be \\(100 - 2 \\times 10 = 80\\)",
          "In the equation above replace \\(s(p)\\) by 80 and p by 10 and solve for \\(a\\) in \\(80 = 100 + a \\times 10\\)")
uiOutput("quiz_1.02")
```

# Derivative of a function

...

<div style='background-color:rgba(150, 70, 255, .1); padding:20px 20px; margin-top:10px; width:100%; border:1px solid black'>

For more on derivatives, please watch the following videos:

```{r}
bs_modal('Derivatives','derivative', inclMD("./cases/modals/derivatives.md"))
```
</div>

```{r}
make_quiz("1.03", "What are the profits generated at a price of $5.50?",
          paste0("$",c("150.00","152.50","155.00","157.50","160.00")),
          "$157.50",
          "Replace the price p with 5.5 in the profit function to obtain \\((100 - 10 \\times 5.5) \\times (5.5 - 2) = 157.5\\)",
          "Replace the price p with 5.5 in the profit function")

uiOutput("quiz_1.03")
```
